version: '3.5'
services:
  mediathekview:
    image: conrad784/mediathekview-webinterface
    container_name: mediathekview
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "5800:5800"
    volumes:
      - "/did/mediathek:/config:rw"
      - "/mnt/hdds/media/mediathek:/output:rw"
    environment:
       - "USER_ID=568"
       - "GROUP_ID=568"
  mirror:
      build: 
          context: .
          dockerfile: apt-mirror.Dockerfile
      command: bash -c "apt-mirror && bash /apt-mirror/postmirror.sh"
      volumes:
          - "/did/mirror/mirror:/var/spool/apt-mirror"  
  server:
      build:
          context: .
          dockerfile: nginx.Dockerfile
      restart: always
      command: [nginx-debug, '-g', 'daemon off;']
      volumes:
          - "/did/mirror/mirror/mirror:/mirror:ro"
      ports:
          - "8080:80"
  p2pool:
    image: ghcr.io/sethforprivacy/p2pool:latest
    restart: unless-stopped
    container_name: p2pool
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    tty: true
    stdin_open: true
    volumes:
      - /did/p2pool:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    ports:
      - 3333:3333
      - 37889:37889
    command: >-
      --wallet "43Ye68LVLqsbss35nQH3LdP6j5R1kziDDcFHWeB93VDTUtQDsc2PBe3dowrVjZa8M1Z7Jx3ysBEbd2nnneN9A86224bpDKv"
      --stratum "0.0.0.0:3333" --p2p "0.0.0.0:37889" --zmq-port "18084"
      --loglevel "0" --addpeers "65.21.227.114:37889,node.sethforprivacy.com:37889"
      --host "p2pmd.xmrvsbeast.com" --mini
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /did/peppermint_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 51531351a53s1d531a53s1d53a1s5d31a35sd1
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$API_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "51531351a53s1d531a53s1d53a1s5d31a35sd1"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
